export const GET_FRUITS_VEG_DATA_REQUEST = 'GET_FRUITS_VEG_DATA_REQUEST';
export const GET_FRUITS_VEG_DATA_SUCCESS = 'GET_FRUITS_VEG_DATA_SUCCESS';
export const GET_FRUITS_VEG_DATA_FAILURE = 'GET_FRUITS_VEG_DATA_FAILURE';
